var mk_mk = {
    Save: "Зачувај",
    "Save all": "Зачувај сè",
    Rename: "Преименувај",
    Open: "Отвори",
    Edit: "Уреди",
    Delete: "Избриши",
    Folder: "Папка",
    "Add New": "Додај ново",
    Size: "Големина",
    Date: "Датум",
    "back to parent folder": "Назад кон родителската папка",
    Download: "Преземи",
    Type: "Тип",
    Information: "Информации",
    Files: "Датотеки",
    Table: "Табела",
    Cards: "Картички",
    Total: "Вкупно",
    "Are you sure ?": "Дали си сигурен?",
    Details: "Детали",
    "Enter a new name": "Внесете ново име",
    Add: "Додај",
    "Select something": "Изберете нешто.",
    "Download file": "Преземи датотека",
    Preview: "Преглед",
    Refresh: "Освежи",
    "Are you sure you want to exit without saving?": "Дали сте сигурни дека сакате да излезете без да ги зачувате промените?",
    "Save before closing?": "Зачувај пред затворање?",
    Copy: "Копирај",
    Cut: "Исечи",
    Paste: "Залепи",
    "Deleting...": "Бришење...",
    "Copying...": "Копирање...",
    "Moving...": "Преместување...",
    Folders: "Папки",
    "Search results": "Резултати од пребарувањето",
    "Search results in": "Резултати од пребарувањето во",
    "Search files and folders": "Пребарувајте датотеки и папки",
    "Add new file": "Додај нова датотека",
    "Add new folder": "Додај нова папка",
    "Upload file": "Прикачи датотека",
    folder: "папка",
    file: "датотека",
    archive: "архива",
    audio: "аудио",
    image: "слика",
    video: "видео",
    code: "код",
    document: "документ",
    of: "од",
    used: "искористено",
    "Open item location": "Отвори ја локацијата на ставката",
    "Are you sure you want to delete": "Дали сте сигурни дека сакате да избришете?",
    "these items:": "овие ставки:",
    "this item:": "оваа ставка:",
    "Delete files": "Избриши датотеки",
    and: "и",
    "more file(s)": "повеќе датотеки",
    "Close the editor": "Затвори уредувач",
    "Close this file": "Затвори ја оваа датотека",
    "Owner": "Сопственик",
    "Permissions": "Дозволи",
    "Change Permissions": "Промени дозволи",
    "Set": "Постави",
    "Extract": "Отпакувај",
    "Extract directory": "Распакувај го директориумот",
    "Extracting...": "Распакување...",
    "Compress": "Компресирај",
    "Compressing...": "Компресирање...",
};
